apiVersion: v1
kind: Service
metadata:
  name: goservice
spec:
  selector:
    app: goserver
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      name: goserver-service
      protocol: TCP